# A variable to store all the modrinth slugs
modlist=(
    architectury-api
    badoptimizations
    betteraddserver
    better-mount-hud
    bettergrassify
    capes
    chat-heads
    chat-impressive-animation
    cloth-config
    clumps
    continuity
    controlling
    crash-assistant
    cubes-without-borders
    debugify
    dynamic-fps
    entity-model-features
    entitytexturefeatures
    entityculling
    euphoria-patches
    fabric-api
    fabric-language-kotlin
    fast-ip-ping
    #fastquit # Actions build
    ferrite-core
    forge-config-api-port
    graceful-packets
    immediatelyfast
    iris
    krypton
    lambdynamiclights
    #language-reload # Currently incompatible
    lithium
    main-menu-credits
    mixintrace
    modmenu
    modelfix
    #mutils # Have been using my own (still not accepted) PR since 1.21.8
    morechathistory
    moreculling
    no-chat-reports
    optigui
    packet-fixer
    placeholder-api
    puzzle
    reeses-sodium-options
    rrls
    resourcify
    scalablelux
    scribble
    searchables
    serverpingerfixer
    shulkerboxtooltip
    shut-up-realms
    simple-hud-enhanced
    smooth-scroll
    sodium
    sodium-extra
    spark
    stackdeobf
    #threadtweak # Actions build
    tooltip-scroll
    viafabricplus
    yacl
    yosbr
    zoomify
)