name = "Sherbert"
author = "Welsey_"
version = "5.4.0"
slug = "sherbert"

[targets]
mc = "26.2"
mc-acceptable-versions = '"26.1"'
fabric = "0.19.3"

[content]
    [all]
        remotes = [
            "alternate-current",
            "animaticarefabricated",
            "aseprite-fonts",
            "asynclogger",
            "asyncparticles",
            "audiothrottle",
            "bettergrassify",
            "cape-provider",
            "chat-heads",
            "chat-reporting-helper",
            "cloth-config",
            "complementary-reimagined",
            "configmanager",
            "continuity",
            "controlling",
            "crash-assistant",
            "cubes-without-borders",
            "debugify",
            "dynamic-fps",
            "e4mc",
            "emojis",
            "entity-model-features",
            "entitytexturefeatures",
            "fabric-language-kotlin",
            "fast-ip-ping",
            "fastquit",
            "ferrite-core",
            "forge-config-api-port",
            "gnetum",
            "graceful-packets",
            "immediatelyfast",
            "iris",
            "irissearch",
            "ixeris",
            "jasione",
            "lambdynamiclights",
            "language-reload",
            "leave-my-bars-alone",
            "lithium",
            "main-menu-credits",
            "mellow",
            "mixintrace-reborn",
            "modernfix-mvus",
            "modmenu",
            "modmenu-filter",
            "morechathistory",
            "moreculling",
            #"mutilsc",
            "no-chat-reports",
            "obe",
            "optigui",
            "packed-packs",
            "packet-fixer",
            "paginatedadvancements",
            "placeholder-api",
            "polytone",
            "progresspeek",
            "puzzle",
            "quick-pack",
            "reeses-sodium-options",
            "respackopts",
            "resourcify",
            "rethoughted-gui",
            "rrls",
            "scalablelux",
            "screenshot-overhaul",
            "scribble",
            "searchables",
            "shut-up-realms",
            "simple-hud-enhanced",
            "skyboxify",
            "smooth-scroll",
            "sodium",
            "sodium-extra",
            "sodium-shadowy-path-blocks",
            "spark",
            "taskmanager",
            "tooltip-scroll",
            "translations-for-sodium",
            "viafabricplus",
            "vmp-fabric",
            "yacl",
            "zfastnoise",
            "zoomify",
        ]

        [[content.nonremote]]
            file = "resourcepacks/Sherbert_Colors.zip"
            note = "Provides colors and other UI stuff"

    [fabric]
        remotes = [
            "fabric-api"
        ]

        [[content.pinned_remote]]
            id = "sodium"
            version = "2Yom1N68"
            allow_different_mc = false
            note = "Iris only supports full Sodium versions, not alphas."

        [[content.remote_exception]]
            id = "mutilsc"
            reason = "ModpackUtils Continued dosen't have a Modrinth page right now."
            file = "mods/mutilsc-1.2.0+fabric.26.2.jar"

[variablevalues]
    version = [
        "config/mutils/mutils.json5",
    ]

[forcedconfigs]
    files = [
        "config/modpack_defaults/config/isxander-main-menu-credits.json",
        "config/modpack_defaults/config/modmenu.json",
        "config/modpack_defaults/config/rrls.toml"
    ]

    folders = [
        "config/modpack_defaults/config/crash_assistant",
        "config/modpack_defaults/config/mutils"
    ]