# Stores information about modpack
info=(
    name="Sherbert"
    author="Welsey_"
    version="4.0.0-beta1"
)

# Stores all the modrinth slugs. If incompatible, add 'Currently incompatible' comment. If it's manually included, comment out its line and leave a note
modlist=(
    alternate-current
    animated-loading-screen
    aseprite-fonts
    badoptimizations
    betteraddserver
    better-block-entities
    better-clouds
    better-mount-hud
    bettergrassify
    capes
    chat-heads
    chat-impressive-animation
    chunks-fade-in
    cloth-config
    complementary-reimagined
    continuity
    controlling
    crash-assistant
    cubes-without-borders
    debugify
    dynamic-fps
    entity-model-features
    entitytexturefeatures
    entityculling
    fabric-api
    fabric-language-kotlin
    fast-ip-ping
    fastquit
    ferrite-core
    forge-config-api-port
    graceful-packets
    hold-that-chunk
    immediatelyfast
    iris
    krypton
    lambdynamiclights
    language-reload
    lithium
    main-menu-credits
    mellow
    mixintrace
    modernfix-mvus
    modmenu
    modelfix
    mutils # Have been using my own (still not accepted) PR since 1.21.8
    morechathistory
    moreculling
    no-chat-reports
    noisiumforked
    optigui
    packet-fixer
    placeholder-api
    puzzle
    reeses-sodium-options
    rrls
    resourcify
    rethoughted-gui
    scalablelux
    scribble
    searchables
    serverpingerfixer
    shut-up-realms
    simple-hud-enhanced
    smooth-scroll
    sodium
    sodium-shadowy-path-blocks
    sodium-extra
    spark
    stackdeobf
    threadtweak
    tooltip-scroll
    vmp-fabric
    viafabricplus
    yacl
    yosbr
    zoomify
)