name = "Sherbert"
author = "Welsey_"
version = "5.1.0"

[targets]
mc = "26.2"
neo = "none"
fabric = "0.19.3"

[content]
    [all]
        remotes = [
            "alternate-current",
            "animated-mojang-logo",
            "animaticarefabricated",
            "aseprite-fonts",
            #"audiothrottle",
            "badoptimizations",
            #"betteraddserver",
            "better-clouds",
            "better-mount-hud",
            "bettergrassify",
            "cape-provider",
            "chat-heads",
            "chat-impressive-animation",
            "chat-reporting-helper",
            "chunks-fade-in",
            "cloth-config",
            "configmanager",
            "complementary-reimagined",
            "continuity",
            "controlling",
            "crash-assistant",
            "cubes-without-borders",
            "debugify",
            "dynamic-fps",
            "e4mc",
            "emojis",
            "entity-model-features",
            "entitytexturefeatures",
            "entityculling",
            "fabric-language-kotlin",
            "fast-ip-ping",
            #"fastquit",
            "ferrite-core",
            "fism",
            "forge-config-api-port",
            "graceful-packets",
            "hold-that-chunk-v2",
            "immediatelyfast",
            "iris",
            "irissearch",
            "ixeris",
            #"krypton",
            "lambdynamiclights",
            "language-reload",
            "lithium",
            "main-menu-credits",
            "mellow",
            "mixintrace-reloaded",
            "modernfix-mvus",
            "modmenu",
            "morechathistory",
            "moreculling",
            #"mutilsc",
            "no-chat-reports",
            "noisiumforked",
            "obe",
            "optigui",
            "packet-fixer",
            "paginatedadvancements",
            "placeholder-api",
            "puzzle",
            "quick-pack",
            #"reeses-sodium-options",
            "rrls",
            "resourcify",
            "rethoughted-gui",
            "scalablelux",
            "scribble",
            "searchables",
            "serverpingerfixer",
            "shut-up-realms",
            "simple-hud-enhanced",
            "skyboxify",
            #"smart-particles",
            "smooth-scroll",
            #"sodium",
            "sodium-shadowy-path-blocks",
            "sodium-extra",
            "spark",
            #"stackdeobf",
            #"taskmanager",
            #"threadtweak",
            "tooltip-scroll",
            "translations-for-sodium",
            "vmp-fabric",
            "viafabricplus",
            "yacl",
            "zfastnoise",
            "zoomify"
        ]

        # [[content.remote_exception]]
        #     id = "modrinth-project-id-or-slug"
        #     reason = "Example usage of this feature"
        #     file = "n/a"
        #     date = "n/a"

        [[content.remote_exception]]
            id = "mutilsc"
            reason = "ModpackUtils Continued dosen't have a Modrinth page right now."
            file = "mods/mutilsc-1.2.0+fabric.26.2.jar"

        # [[content.pinned_remote]]
        #     id = "modrinth-project-id-or-slug"
        #     version = "modrinth-version-id"
        #     allow_different_mc = true
        #     note = "Optional reason for pinning this exact version"

        [[content.pinned_remote]]
            id = "sodium"
            version = "3QgJXuSK"
            allow_different_mc = false
            note = "Pinned 0.9.0 because 0.9.1 causes incompatibility with latest Iris at time of writing."

        [[content.pinned_remote]]
            id = "reeses-sodium-options"
            version = "zD41FWKT"
            allow_different_mc = false
            note = "Pins RSO to avoid problems with requiring the newest Sodium."

        [[content.nonremote]]
            file = "resourcepacks/Sherbert_Colors.zip"
            note = "Provides colors and other UI stuff"

    [fabric]
        remotes = [
            "fabric-api"
        ]

    [neo]

[variablevalues]
    version = [
        "config/mutils/mutils.json5",
    ]

[forcedconfigs]
    files = [
        "config/modpack_defaults/config/animated-mojang-logo.json",
        "config/modpack_defaults/config/isxander-main-menu-credits.json",
        "config/modpack_defaults/config/modmenu.json",
        "config/modpack_defaults/config/rrls.toml"
    ]

    folders = [
        "config/modpack_defaults/config/crash_assistant",
        "config/modpack_defaults/config/mutils"
    ]