name = "Sherbert"
author = "Welsey_"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15322eabb270149efefdd19e6551e0c40ce3de4098c6c4729441216a60d22e11"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.11", "1.21.10", "1.21.9", "1.21.8"]
