name = "Sherbert"
author = "Welsey_"
version = "4.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a9eec52e2ef34d0d4b44a1dcfdbfe84c88b7e15c9e44f60ca77d7e10c1ccc52"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.11", "1.21.10", "1.21.9", "1.21.8"]
